language: node_js
node_js:
  - "12"

install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb
script:
 - echo "Deploy To Firebase CI"
 - hugo
install:
  - npm install -g firebase-tools
after_success:
  - hugo && firebase deploy --only hosting --project pulumi-hugo-cn --token $FIREBASE_TOKEN